### ISSUE TITLE
The term 'bounce' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and  try again.

### ISSUE THREAD

**Issue by sslotsky** [jvukovich/bounce#20]
I created a new class library called `Bounce` within my solution and added the nuget package to just that project. The `Bounce` library contains a single class

```
using Bounce.Framework;
using System;

namespace Bounce
{
    public class Class1
    {
        [Task]
        public void HelloWorld()
        {
            Console.WriteLine("hello, world!");
        }
    }
}
```

I've set `Bounce` as my startup project in the Solution Explorer and also as my default project in my package manage console. When I rebuild, I see the following output:

> > > 1>  Bounce -> C:\Users\Sam\Source\Workspaces\SaffireCMS\Main\Bounce\bin\Debug\Bounce.dll
> > > ========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

However, running `> bounce` produces the error

> The term 'bounce' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and  try again.

**Comment by jvukovich** [comment]
Closing out all PRs and issues. A new version of Bounce will be coming which will deprecate prior versions.
